baseurl = "https://drcoffee84.github.io/nahir/"
title = "Nahir"
theme = "hugo-universal-theme"
languageCode = "es-es"
defaultContentLanguage = "es"
disqusShortname = "nahir"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]
# Main menu
[[menu.main]]
    name       = "Inicio"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Servicios"
    identifier = "menu.portfolio"
    url        = "/img/template-homepage.png"
    weight     = 2

[[menu.main]]
    name       = "Contacto"
    identifier = "menu.allpages"
    url        = "/contact"
    weight     = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "https://www.instagram.com/bestconsultoriaygestion/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:consultoriaygestionbest@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    instagram_site = "" # the Facebook handle of your site ('https://www.instagram.com/bestconsultoriaygestion/')
    default_sharing_image = "img/sharing-default.png"

 
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false


    about_us = "<p>Somos una consultora integral conformada por un equipo de jóvenes profesionales, cuyo foco se encuentra en el Reclutamiento y Selección de personal, Contabilidad de Gestión y Asesoramiento Impositivo. Con nuestro profesionalismo nos dedicamos a cubrir las necesidades de las empresas clientes como así también de aquellos que se encuentran en búsqueda laboral activa.</p>"
    copyright = "Copyright (c) 2023 - TBD"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"


# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    title = "Sobre nosotras"
    subtitle = "Somos una consultora integral conformada por un equipo de jóvenes profesionales, cuyo foco se encuentra en el Reclutamiento y Selección de personal, Contabilidad de Gestión y Asesoramiento Impositivo. Con nuestro profesionalismo nos dedicamos a cubrir las necesidades de las empresas clientes como así también de aquellos que se encuentran en búsqueda laboral activa."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
